services:
  - type: web
    name: ethfs-web
    region: ohio
    runtime: node
    rootDir: packages/web
    buildCommand: pnpm install && pnpm build
    startCommand: pnpm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ethfs-shovel-db
          property: connectionString

  - type: web
    name: ethfs-shovel
    region: ohio
    runtime: docker
    dockerfilePath: ./shovel/Dockerfile
    dockerContext: ./shovel
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ethfs-shovel-db
          property: connectionString

  # - type: web
  #   name: ethfs-ponder
  #   region: ohio
  #   runtime: node
  #   rootDir: packages/ponder
  #   buildCommand: pnpm install
  #   startCommand: pnpm start
  #   envVars:
  #     - key: DATABASE_URL
  #       fromDatabase:
  #         name: ethfs-ponder-db
  #         property: connectionString

databases:
  - name: ethfs-shovel-db
    plan: starter
    region: ohio

  # - name: ethfs-ponder-db
  #   plan: starter
  #   region: ohio
