services:
  - type: web
    name: ethfs-web
    region: ohio
    runtime: node
    rootDir: packages/web
    buildCommand: npm install -g pnpm@9 && pnpm install && pnpm build
    startCommand: pnpm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ethfs-shovel-db
          property: connectionString

  - type: web
    name: ethfs-shovel
    region: ohio
    runtime: docker
    maxShutdownDelaySeconds: 1
    rootDir: shovel
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ethfs-shovel-db
          property: connectionString

databases:
  - name: ethfs-shovel-db
    plan: starter
    region: ohio
