services:
  - type: web
    name: ethfs-shovel
    region: ohio
    runtime: docker
    dockerfilePath: ./shovel/Dockerfile
    dockerContext: ./shovel
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ethfs-shovel
          property: connectionString

  - type: web
    name: ethfs-ponder
    region: ohio
    runtime: node
    rootDir: packages/ponder
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ethfs-ponder
          property: connectionString

databases:
  - name: ethfs-shovel
    plan: starter
    region: ohio

  - name: ethfs-ponder
    plan: starter
    region: ohio
