services:
  - type: web
    name: shovel
    region: ohio
    runtime: docker
    dockerfilePath: ./packages/shovel/Dockerfile
    dockerContext: ./packages/shovel
    autoDeploy: false
    envVars:
      - key: PASSWORD
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: shovel
          property: connectionString
databases:
  - name: shovel
    plan: standard
    region: ohio
